#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors");
for (var n = 1; n <= 12; n++) {
  console.log(n + c.multi("Badger"));
}

for (var n = 1; n <= 3; n++) {
  console.log(n + c.red + "Mushroom")
}



